DATA:
    DATASET: cifar10 # omniglot, cifar10, diy

    DATA_PATH: /home/charon/project/representation_paths/data/  # path to all datasets (mnist, cifar10, diy)
    LAEBL_PATH: /home/charon/project/representation_paths/data/  # path to all datasets (mnist, cifar10, diy)

    NUM_TRAIN: -1 # -1 means all data
    NUM_TEST: 10000
    TRAIN_BATCH_SIZE: 50
    VALID_BATCH_SIZE: 256
    TEST_BATCH_SIZE: 10000

    TRAIN_SIZE: 0.9

    # Augmentation
    AUG: False
    AUG_PROB: 0.5
    IMG_MEAN: (0.485, 0.456, 0.406)
    IMG_STD: (0.229, 0.224, 0.225)

    # Label
    CLASS_NUM: 10

    NUM_WORKERS: 24

MODEL:
    NAME: resnet  # fcn, resnet, resnet_p,
    INPUT_SIZE: 3072
    HIDDEN_SIZE: 64
    PROJECTION_SIZE: 64  # used for resnet with projection
    NUM_HIDDEN_LAYERS: 2  # total layers = input + hidden + output
    OUTPUT_SIZE: 10


    DROPOUT: 0.0
    ACTIVATION: relu  # relu, tanh, sigmoid, leaky_relu, prelu
    L1: 0.0
    L2: 0.0

    SAVE_DIR: /home/charon/project/representation_paths/models/



OPTIMIZATION:
    LOSS: cross_entropy  # cross_entropy, binary_cross_entropy, l1, l2,

    BATCH_SIZE_PER_GPU: 1
    MAX_EPOCHS: 10

    # OPTIMIZER
    OPTIMIZER: Adam  # Adam, SGD, RMSprop
    LR: 0.001
    WEIGHT_DECAY: 0.0
    MOMENTUM: 0.9

    # SCHEDULER
    LR_SCHEDULER: constant  # cyclic, plateau, cosine, step
    LR_DECAY_STEPS: 20
    LR_DECAY_RATE: 0.5
    LR_DECAY_MIN_LR: 0.00001
    PATIENCE: 20
    ACC_GRADIENT_STEPS: 1

LOG:
    PATH: /home/charon/project/representation_paths/log/

SEED: 42